#!/usr/bin/env python3
"""TypeScript/JavaScript AST rules - runs ast-grep on Edit/Write targets.

Only triggers for .ts, .tsx, .js, .jsx files.
Generated by torad-toolkit, version 1.0.0
"""
import json
import subprocess
import tempfile
import sys
from pathlib import Path


def applies(data: dict) -> bool:
    """Only run for Edit/Write on TS/JS files."""
    tool = data.get("tool_name", "")
    if tool not in ("Edit", "Write", "MultiEdit"):
        return False

    file_path = data.get("tool_input", {}).get("file_path", "")
    return any(file_path.endswith(ext) for ext in (".ts", ".tsx", ".js", ".jsx"))


def proposed_content(data: dict) -> str | None:
    """The bytes this tool call WOULD write.

    A PreToolUse hook that scans `file_path` on disk inspects the OLD content:
    for a Write to a new path there is no file at all, and for an Edit the
    edit has not been applied yet. Either way the anti-pattern being
    introduced is invisible and the gate passes everything. Reconstruct the
    post-edit text instead, and scan that.
    """
    tool = data.get("tool_name", "")
    ti = data.get("tool_input", {}) or {}
    path = Path(ti.get("file_path", ""))

    if tool == "Write":
        return ti.get("content", "")

    try:
        current = path.read_text() if path.exists() else ""
    except OSError:
        return None

    if tool == "Edit":
        old, new = ti.get("old_string", ""), ti.get("new_string", "")
        if old and old not in current:
            return None  # anchor will not match; let the tool report that
        return current.replace(old, new, -1 if ti.get("replace_all") else 1)

    if tool == "MultiEdit":
        for e in ti.get("edits", []) or []:
            old, new = e.get("old_string", ""), e.get("new_string", "")
            if old and old not in current:
                return None
            current = current.replace(old, new, -1 if e.get("replace_all") else 1)
        return current

    return None


def _scan(sgconfig: Path, text: str, name: str) -> list:
    """Run ast-grep over `text`, at a temp path MIRRORING the real one.

    `name` is the path relative to the project root, not the basename. Rules
    scope by path glob, and a probe at /tmp/xxxx/Foo.ts satisfies `**/Foo.ts`
    but not `**/src/**`, so a flat basename made the write-time gate disagree
    with the batch scan on every path-scoped rule.
    """
    with tempfile.TemporaryDirectory() as td:
        probe = Path(td) / name
        probe.parent.mkdir(parents=True, exist_ok=True)
        probe.write_text(text)
        result = subprocess.run(
            ["ast-grep", "scan", "--config", str(sgconfig), str(probe), "--json"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    try:
        return json.loads(result.stdout) if result.stdout else []
    except json.JSONDecodeError:
        return []


def _key(v: dict) -> tuple:
    """Identify a violation by rule and DECLARATION line.

    Not by line NUMBER: those shift whenever anything above them changes, so
    every violation below an insertion would read as newly introduced.

    Not by the WHOLE matched span either. A rule that matches a whole
    declaration means editing anything inside an already-flagged one — a
    default argument, a call site in its body — changes the matched text. The
    old key vanishes, a new one appears, and a pre-existing violation is
    reported as introduced. That blocks the call-site updates cleanup is made
    of, inside precisely the declarations still awaiting cleanup. The first
    line of a match is the declaration, which stays stable while its
    parameters and body change.
    """
    lines = [ln.strip() for ln in (v.get("lines") or "").splitlines() if ln.strip()]
    return (v.get("ruleId", "?"), lines[0] if lines else "")


def _introduced(before: list, after: list) -> list:
    """Violations the edit ADDS, by multiset difference."""
    from collections import Counter

    prior = Counter(_key(v) for v in before)
    new = []
    for v in after:
        k = _key(v)
        if prior[k] > 0:
            prior[k] -= 1  # matched a pre-existing one; grandfathered
        else:
            new.append(v)
    return new


def run(data: dict) -> dict:
    """Run ast-grep rules on the target file."""
    file_path = data.get("tool_input", {}).get("file_path", "")

    # Find project root (where .rules/typescript exists)
    path = Path(file_path).resolve()
    root = path.parent
    while root != root.parent:
        if (root / ".rules" / "typescript" / "ast-grep" / "sgconfig.yml").exists():
            break
        root = root.parent
    else:
        return {"continue": True}  # No rules found

    sgconfig = root / ".rules" / "typescript" / "ast-grep" / "sgconfig.yml"

    content = proposed_content(data)
    if content is None:
        return {"continue": True}

    src = Path(file_path)
    before_text = src.read_text() if src.exists() else ""

    try:
        # INCREMENTAL. Scan the file as it is now and as it WOULD be, and act
        # only on what the edit introduces. A gate that fires on pre-existing
        # debt blocks the refactor that removes it: every edit to a file with
        # nine violations is denied, including the edit deleting one of them.
        # Pre-existing instances are grandfathered.
        # Relative to the project root, so path-scoped ignores resolve — see _scan.
        try:
            rel = str(src.resolve().relative_to(root))
        except ValueError:
            rel = src.name

        before = _scan(sgconfig, before_text, rel) if before_text else []
        after = _scan(sgconfig, content, rel)

        violations = _introduced(before, after)

        if not violations:
            return {"continue": True}

        # rules/ ships severity "error" (LAW, blocking); rules-style/ ships
        # "warning" (tenets, advisory). Split on it, or a style preference
        # denies a write and the first thing an author does is switch the
        # gate off.
        errors = [v for v in violations if v.get("severity") == "error"]
        warnings = [v for v in violations if v.get("severity") != "error"]

        def fmt(vs):
            out = []
            for v in vs[:8]:
                rule = v.get("ruleId", "unknown")
                line = v.get("range", {}).get("start", {}).get("line", "?")
                text = (v.get("lines") or "").strip().splitlines()[:1]
                snippet = f"  {text[0].strip()}" if text else ""
                out.append(f"  - {rule} at line {line}\n{snippet}".rstrip())
            if len(vs) > 8:
                out.append(f"  ... and {len(vs) - 8} more")
            return "\n".join(out)

        if errors:
            # DENY. A LAW rule that reports and lets the write through is not a
            # gate; it reads as coverage and gets cited as one.
            msg = (
                f"BLOCKED by {len(errors)} TypeScript LAW rule violation(s) "
                f"(.rules/typescript/ast-grep/rules/):\n"
                + fmt(errors)
                + "\n\nFix the code. If the rule is wrong, fix the rule and add a "
                "fixture proving it; do not annotate past it."
            )
            if warnings:
                msg += f"\n\nAlso {len(warnings)} style warning(s) (non-blocking):\n" + fmt(warnings)
            # `continue` stays TRUE: this denies the write, it does not end the session.
            # `continue: false` is the protocol's kill switch — it aborts the whole turn,
            # so one refused edit would stop whatever work was in flight.
            return {"continue": True, "decision": "block", "message": msg}

        return {
            "continue": True,
            "message": f"{len(warnings)} TypeScript style warning(s) (non-blocking):\n" + fmt(warnings),
        }

    # FAIL CLOSED. Every branch below is a gate that did not run, and a gate that did
    # not run must never read as a gate that found nothing — that is the fake-green this
    # whole pack exists to prevent. Each blocks with a reason naming the actual cause.
    except subprocess.TimeoutExpired:
        return {
            "continue": True, "decision": "block",
            "message": "[typescript_rules] ast-grep timed out after 10s, so the TS LAW "
                       "rules did NOT run on this write. Refusing it rather than "
                       "allowing it unchecked.",
        }
    except FileNotFoundError:
        return {
            "continue": True, "decision": "block",
            "message": "[typescript_rules] ast-grep is not installed, so the TS LAW "
                       "rules did NOT run on this write. Install it — an unenforced "
                       "gate must not read as a passing one.",
        }
    except Exception as e:
        print(f"[typescript_rules] error: {e}", file=sys.stderr)
        return {
            "continue": True, "decision": "block",
            "message": f"[typescript_rules] raised {type(e).__name__}: {e}, so the TS "
                       "LAW rules did NOT run on this write. Refusing it rather than "
                       "allowing it unchecked.",
        }


if __name__ == "__main__":
    try:
        data = json.loads(sys.stdin.read())
        if applies(data):
            result = run(data)
            print(json.dumps(result))
        else:
            print(json.dumps({"continue": True}))
    except Exception as e:
        print(f"[typescript_rules] fatal: {e}", file=sys.stderr)
        print(json.dumps({"continue": True}))
