// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionPrint is an autogenerated mock type for the DecisionPrint type
type DecisionPrint struct {
	mock.Mock
}

// Print provides a mock function with given fields: modelPath, ids, titles, sections
func (_m *DecisionPrint) Print(modelPath string, ids []string, titles []string, sections map[string]bool) error {
	ret := _m.Called(modelPath, ids, titles, sections)

	if len(ret) == 0 {
		panic("no return value specified for Print")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, []string, map[string]bool) error); ok {
		r0 = rf(modelPath, ids, titles, sections)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionPrint creates a new instance of DecisionPrint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionPrint(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionPrint {
	mock := &DecisionPrint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
