// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionAdd is an autogenerated mock type for the DecisionAdd type
type DecisionAdd struct {
	mock.Mock
}

// Add provides a mock function with given fields: modelPath, titles
func (_m *DecisionAdd) Add(modelPath string, titles []string) error {
	ret := _m.Called(modelPath, titles)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(modelPath, titles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionAdd creates a new instance of DecisionAdd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionAdd(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionAdd {
	mock := &DecisionAdd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
