// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionLink is an autogenerated mock type for the DecisionLink type
type DecisionLink struct {
	mock.Mock
}

// Link provides a mock function with given fields: modelPath, sourceID, sourceTitle, targetID, targetTitle, tag, reverseTag
func (_m *DecisionLink) Link(modelPath string, sourceID string, sourceTitle string, targetID string, targetTitle string, tag string, reverseTag string) error {
	ret := _m.Called(modelPath, sourceID, sourceTitle, targetID, targetTitle, tag, reverseTag)

	if len(ret) == 0 {
		panic("no return value specified for Link")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, string) error); ok {
		r0 = rf(modelPath, sourceID, sourceTitle, targetID, targetTitle, tag, reverseTag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionLink creates a new instance of DecisionLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionLink {
	mock := &DecisionLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
