// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionDecide is an autogenerated mock type for the DecisionDecide type
type DecisionDecide struct {
	mock.Mock
}

// Decide provides a mock function with given fields: modelPath, id, title, option, reason, author, enforceOption
func (_m *DecisionDecide) Decide(modelPath string, id string, title string, option string, reason string, author string, enforceOption bool) error {
	ret := _m.Called(modelPath, id, title, option, reason, author, enforceOption)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, bool) error); ok {
		r0 = rf(modelPath, id, title, option, reason, author, enforceOption)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionDecide creates a new instance of DecisionDecide. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionDecide(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionDecide {
	mock := &DecisionDecide{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
