// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionList is an autogenerated mock type for the DecisionList type
type DecisionList struct {
	mock.Mock
}

// ListDecisions provides a mock function with given fields: modelPath, filters, format
func (_m *DecisionList) ListDecisions(modelPath string, filters map[string][]string, format string) error {
	ret := _m.Called(modelPath, filters, format)

	if len(ret) == 0 {
		panic("no return value specified for ListDecisions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string][]string, string) error); ok {
		r0 = rf(modelPath, filters, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionList creates a new instance of DecisionList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionList(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionList {
	mock := &DecisionList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
