// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionTag is an autogenerated mock type for the DecisionTag type
type DecisionTag struct {
	mock.Mock
}

// Tag provides a mock function with given fields: modelPath, id, title, tags
func (_m *DecisionTag) Tag(modelPath string, id string, title string, tags []string) error {
	ret := _m.Called(modelPath, id, title, tags)

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []string) error); ok {
		r0 = rf(modelPath, id, title, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionTag creates a new instance of DecisionTag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionTag(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionTag {
	mock := &DecisionTag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
