// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionRule is an autogenerated mock type for the DecisionRule type
type DecisionRule struct {
	mock.Mock
}

// Rule provides a mock function with given fields: modelPath, id, title, outputPath
func (_m *DecisionRule) Rule(modelPath string, id string, title string, outputPath string) error {
	ret := _m.Called(modelPath, id, title, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Rule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(modelPath, id, title, outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionRule creates a new instance of DecisionRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionRule {
	mock := &DecisionRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
