// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionRevise is an autogenerated mock type for the DecisionRevise type
type DecisionRevise struct {
	mock.Mock
}

// ReviseDecision provides a mock function with given fields: modelPath, id, title
func (_m *DecisionRevise) ReviseDecision(modelPath string, id string, title string) error {
	ret := _m.Called(modelPath, id, title)

	if len(ret) == 0 {
		panic("no return value specified for ReviseDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(modelPath, id, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionRevise creates a new instance of DecisionRevise. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionRevise(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionRevise {
	mock := &DecisionRevise{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
