// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelRebuildIndex is an autogenerated mock type for the ModelRebuildIndex type
type ModelRebuildIndex struct {
	mock.Mock
}

// RebuildIndex provides a mock function with given fields: modelPath
func (_m *ModelRebuildIndex) RebuildIndex(modelPath string) error {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for RebuildIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(modelPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelRebuildIndex creates a new instance of ModelRebuildIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelRebuildIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelRebuildIndex {
	mock := &ModelRebuildIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
