// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelInit is an autogenerated mock type for the ModelInit type
type ModelInit struct {
	mock.Mock
}

// Init provides a mock function with given fields: modelPath
func (_m *ModelInit) Init(modelPath string) error {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(modelPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelInit creates a new instance of ModelInit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelInit(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelInit {
	mock := &ModelInit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
