// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelCopy is an autogenerated mock type for the ModelCopy type
type ModelCopy struct {
	mock.Mock
}

// Copy provides a mock function with given fields: modelPath, targetPath, filters
func (_m *ModelCopy) Copy(modelPath string, targetPath string, filters map[string][]string) error {
	ret := _m.Called(modelPath, targetPath, filters)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string][]string) error); ok {
		r0 = rf(modelPath, targetPath, filters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelCopy creates a new instance of ModelCopy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelCopy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelCopy {
	mock := &ModelCopy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
