// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelValidate is an autogenerated mock type for the ModelValidate type
type ModelValidate struct {
	mock.Mock
}

// Validate provides a mock function with given fields: modelPath
func (_m *ModelValidate) Validate(modelPath string) error {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(modelPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelValidate creates a new instance of ModelValidate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelValidate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelValidate {
	mock := &ModelValidate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
