/**
 * Sync Command — Export current work context for session resume
 * Zero AI tokens — pure shell/JS execution
 *
 * @module commands/sync
 * @see specs/superspec-borrowing-phase1-2-spec.md (AC-16, AC-17)
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'fs';
import { join } from 'path';

const MAX_LINES = 500;

/**
 * Generate context.md from git info and optional workflow state
 * @param {string} projectPath - Project root directory
 * @returns {string} Path to generated context.md
 */
export function generateContext(projectPath) {
  const lines = [];

  lines.push('# Development Context');
  lines.push(`> Auto-generated by \`uds sync\` at ${new Date().toISOString()}`);
  lines.push('> This file helps restore context in a new AI session.');
  lines.push('');

  // ─── Git Status ───
  lines.push('## Git Status');
  lines.push('');

  const branch = gitCmd('git rev-parse --abbrev-ref HEAD', projectPath);
  lines.push(`- **Branch**: ${branch}`);

  const baseBranch = detectBaseBranch(projectPath);
  if (baseBranch && baseBranch !== branch) {
    const commitCount = gitCmd(`git rev-list --count ${baseBranch}..HEAD`, projectPath) || '0';
    lines.push(`- **Base**: ${baseBranch} (+${commitCount} commits)`);
  }

  lines.push('');
  lines.push('### Recent Commits');
  lines.push('');

  const logOutput = gitCmd('git log --oneline -20', projectPath);
  if (logOutput) {
    lines.push(...logOutput.split('\n').map(l => `- ${l}`));
  } else {
    lines.push('(no commits)');
  }
  lines.push('');

  lines.push('### Changed Files');
  lines.push('');

  if (baseBranch && baseBranch !== branch) {
    const diffStat = gitCmd(`git diff --stat ${baseBranch}..HEAD`, projectPath);
    if (diffStat) {
      lines.push('```');
      lines.push(...diffStat.split('\n'));
      lines.push('```');
    }
  } else {
    lines.push('(on base branch, no diff)');
  }
  lines.push('');

  // ─── Workflow State ───
  const workflowState = readWorkflowState(projectPath);
  if (workflowState) {
    lines.push('## Workflow State');
    lines.push('');
    lines.push(...workflowState);
    lines.push('');
  }

  // Truncate to MAX_LINES
  const truncated = lines.slice(0, MAX_LINES);

  // Write to .workflow-state/context.md
  const outputDir = join(projectPath, '.workflow-state');
  mkdirSync(outputDir, { recursive: true });
  const outputPath = join(outputDir, 'context.md');
  writeFileSync(outputPath, truncated.join('\n'), 'utf-8');

  return outputPath;
}

// ─── Helpers ───

function gitCmd(cmd, cwd) {
  try {
    return execSync(cmd, { cwd, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}

function detectBaseBranch(projectPath) {
  // Check for common base branches
  for (const name of ['main', 'master']) {
    const exists = gitCmd(`git rev-parse --verify ${name}`, projectPath);
    if (exists) return name;
  }
  return null;
}

function readWorkflowState(projectPath) {
  const stateDir = join(projectPath, '.workflow-state');
  if (!existsSync(stateDir)) return null;

  const yamlFiles = readdirSync(stateDir)
    .filter(f => f.endsWith('.yaml') && !f.endsWith('.log.yaml'))
    .sort();

  if (yamlFiles.length === 0) return null;

  // Read the most recent state file
  const latestFile = yamlFiles[yamlFiles.length - 1];
  const content = readFileSync(join(stateDir, latestFile), 'utf-8');

  const lines = [];
  // Extract key fields
  const specMatch = content.match(/spec_id:\s*(.+)/);
  const phaseMatch = content.match(/current_phase:\s*(.+)/);
  const statusMatch = content.match(/status:\s*(.+)/);

  if (specMatch) lines.push(`- **Spec**: ${specMatch[1].trim()}`);
  if (phaseMatch) lines.push(`- **Phase**: ${phaseMatch[1].trim()}`);
  if (statusMatch) lines.push(`- **Status**: ${statusMatch[1].trim()}`);

  return lines.length > 0 ? lines : null;
}
