version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    dir: adg
    ldflags:
      - -s -w -X github.com/adr/ad-guidance-tool/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: adg

archives:
  - formats: [binary]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: adr
    name: ad-guidance-tool
  draft: false
  prerelease: auto
  replace_existing_artifacts: true
