// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionComment is an autogenerated mock type for the DecisionComment type
type DecisionComment struct {
	mock.Mock
}

// Commented provides a mock function with given fields: decisionID, author, comment
func (_m *DecisionComment) Commented(decisionID string, author string, comment string) {
	_m.Called(decisionID, author, comment)
}

// NewDecisionComment creates a new instance of DecisionComment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionComment(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionComment {
	mock := &DecisionComment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
