// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionTag is an autogenerated mock type for the DecisionTag type
type DecisionTag struct {
	mock.Mock
}

// Tagged provides a mock function with given fields: decisionID, tags
func (_m *DecisionTag) Tagged(decisionID string, tags []string) {
	_m.Called(decisionID, tags)
}

// NewDecisionTag creates a new instance of DecisionTag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionTag(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionTag {
	mock := &DecisionTag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
