// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	decision "github.com/adr/ad-guidance-tool/internal/domain/decision"

	mock "github.com/stretchr/testify/mock"
)

// DecisionList is an autogenerated mock type for the DecisionList type
type DecisionList struct {
	mock.Mock
}

// Listed provides a mock function with given fields: decisions, format
func (_m *DecisionList) Listed(decisions []decision.Decision, format string) {
	_m.Called(decisions, format)
}

// NewDecisionList creates a new instance of DecisionList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionList(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionList {
	mock := &DecisionList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
