// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionEdit is an autogenerated mock type for the DecisionEdit type
type DecisionEdit struct {
	mock.Mock
}

// Edited provides a mock function with given fields: decisionID
func (_m *DecisionEdit) Edited(decisionID string) {
	_m.Called(decisionID)
}

// NewDecisionEdit creates a new instance of DecisionEdit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionEdit(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionEdit {
	mock := &DecisionEdit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
