// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionDecide is an autogenerated mock type for the DecisionDecide type
type DecisionDecide struct {
	mock.Mock
}

// Decided provides a mock function with given fields: decisionID
func (_m *DecisionDecide) Decided(decisionID string) {
	_m.Called(decisionID)
}

// NewDecisionDecide creates a new instance of DecisionDecide. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionDecide(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionDecide {
	mock := &DecisionDecide{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
