// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionRule is an autogenerated mock type for the DecisionRule type
type DecisionRule struct {
	mock.Mock
}

// RuleGenerated provides a mock function with given fields: decisionID, ruleFilePath
func (_m *DecisionRule) RuleGenerated(decisionID string, ruleFilePath string) {
	_m.Called(decisionID, ruleFilePath)
}

// NewDecisionRule creates a new instance of DecisionRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionRule {
	mock := &DecisionRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
