// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	decision "github.com/adr/ad-guidance-tool/internal/domain/decision"

	mock "github.com/stretchr/testify/mock"
)

// DecisionAdd is an autogenerated mock type for the DecisionAdd type
type DecisionAdd struct {
	mock.Mock
}

// Added provides a mock function with given fields: successes, failures
func (_m *DecisionAdd) Added(successes []*decision.Decision, failures map[string]error) {
	_m.Called(successes, failures)
}

// NewDecisionAdd creates a new instance of DecisionAdd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionAdd(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionAdd {
	mock := &DecisionAdd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
