// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionRevise is an autogenerated mock type for the DecisionRevise type
type DecisionRevise struct {
	mock.Mock
}

// Revised provides a mock function with given fields: originalID, revisedID
func (_m *DecisionRevise) Revised(originalID string, revisedID string) {
	_m.Called(originalID, revisedID)
}

// NewDecisionRevise creates a new instance of DecisionRevise. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionRevise(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionRevise {
	mock := &DecisionRevise{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
