// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	decision "github.com/adr/ad-guidance-tool/internal/domain/decision"

	mock "github.com/stretchr/testify/mock"
)

// DecisionPrint is an autogenerated mock type for the DecisionPrint type
type DecisionPrint struct {
	mock.Mock
}

// Printed provides a mock function with given fields: content, sections
func (_m *DecisionPrint) Printed(content []decision.DecisionContent, sections map[string]bool) {
	_m.Called(content, sections)
}

// NewDecisionPrint creates a new instance of DecisionPrint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionPrint(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionPrint {
	mock := &DecisionPrint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
