// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionLink is an autogenerated mock type for the DecisionLink type
type DecisionLink struct {
	mock.Mock
}

// Linked provides a mock function with given fields: sourceID, targetID, tag, reverseTag
func (_m *DecisionLink) Linked(sourceID string, targetID string, tag string, reverseTag string) {
	_m.Called(sourceID, targetID, tag, reverseTag)
}

// NewDecisionLink creates a new instance of DecisionLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionLink {
	mock := &DecisionLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
