// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelCopy is an autogenerated mock type for the ModelCopy type
type ModelCopy struct {
	mock.Mock
}

// Copied provides a mock function with given fields: source, target, copiedDecisions
func (_m *ModelCopy) Copied(source string, target string, copiedDecisions int) {
	_m.Called(source, target, copiedDecisions)
}

// NewModelCopy creates a new instance of ModelCopy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelCopy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelCopy {
	mock := &ModelCopy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
