// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelValidate is an autogenerated mock type for the ModelValidate type
type ModelValidate struct {
	mock.Mock
}

// ModelValidated provides a mock function with given fields: modelName, indexErr, dataErr
func (_m *ModelValidate) ModelValidated(modelName string, indexErr error, dataErr error) {
	_m.Called(modelName, indexErr, dataErr)
}

// NewModelValidate creates a new instance of ModelValidate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelValidate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelValidate {
	mock := &ModelValidate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
