// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelMerge is an autogenerated mock type for the ModelMerge type
type ModelMerge struct {
	mock.Mock
}

// Merged provides a mock function with given fields: modelAPath, modelBPath, targetPath, mergedDecisions
func (_m *ModelMerge) Merged(modelAPath string, modelBPath string, targetPath string, mergedDecisions int) error {
	ret := _m.Called(modelAPath, modelBPath, targetPath, mergedDecisions)

	if len(ret) == 0 {
		panic("no return value specified for Merged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, int) error); ok {
		r0 = rf(modelAPath, modelBPath, targetPath, mergedDecisions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelMerge creates a new instance of ModelMerge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelMerge(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelMerge {
	mock := &ModelMerge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
