// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelImport is an autogenerated mock type for the ModelImport type
type ModelImport struct {
	mock.Mock
}

// Imported provides a mock function with given fields: sourcePath, targetPath, importedDecisions
func (_m *ModelImport) Imported(sourcePath string, targetPath string, importedDecisions int) error {
	ret := _m.Called(sourcePath, targetPath, importedDecisions)

	if len(ret) == 0 {
		panic("no return value specified for Imported")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(sourcePath, targetPath, importedDecisions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelImport creates a new instance of ModelImport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelImport(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelImport {
	mock := &ModelImport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
