// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelRebuildIndex is an autogenerated mock type for the ModelRebuildIndex type
type ModelRebuildIndex struct {
	mock.Mock
}

// IndexRebuilt provides a mock function with given fields: modelName
func (_m *ModelRebuildIndex) IndexRebuilt(modelName string) {
	_m.Called(modelName)
}

// NewModelRebuildIndex creates a new instance of ModelRebuildIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelRebuildIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelRebuildIndex {
	mock := &ModelRebuildIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
