// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelInit is an autogenerated mock type for the ModelInit type
type ModelInit struct {
	mock.Mock
}

// Initialized provides a mock function with given fields: name
func (_m *ModelInit) Initialized(name string) {
	_m.Called(name)
}

// NewModelInit creates a new instance of ModelInit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelInit(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelInit {
	mock := &ModelInit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
